default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_linetest

development:
  <<: *default

production:
  <<: *default
  host: dpg-cmcklemd3nmc73dc1tb0-a
  database: s_linetest_v3ad
  username: s_linetest_v3ad_user
  password: wiXVwmC7jopewtZvsnM9EjIH6W5S4s2p