default_env: &default
  adapter: postgresql
  encoding: unicode
  database: c_line

development:
  <<: *default

production:
  <<: *default
  host: dpg-cmcjcg821fec73cr93h0-a
  database: s_linetest
  username: s_linetest_user
  password: jbOOcSJGUHzjwx176abHs63dPDBMAKA9